# Generated by Django 5.2.5 on 2026-09-25 13:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_display_name_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('question_count', models.PositiveIntegerField(default=50)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('chapter_quota', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('expired', 'Expired')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField()),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('correct_count', models.PositiveIntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
                ('total_questions', models.PositiveIntegerField(default=0)),
                ('time_taken_seconds', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BoardExamAttemptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('public_snapshot', models.JSONField(default=dict)),
                ('solution_snapshot', models.JSONField(default=dict)),
                ('selected_choice_key', models.CharField(blank=True, default='', max_length=2)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.AddField(
            model_name='boardexam',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='board_exams', to='api.question'),
        ),
        migrations.AddField(
            model_name='boardexamattempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.boardexam'),
        ),
        migrations.AddField(
            model_name='boardexamattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_exam_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardexamattemptitem',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.boardexamattempt'),
        ),
        migrations.AddField(
            model_name='boardexamattemptitem',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='board_exam_items', to='api.question'),
        ),
        migrations.AddConstraint(
            model_name='boardexamattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'in_progress')), fields=('user', 'exam'), name='unique_active_board_exam_attempt'),
        ),
        migrations.AddConstraint(
            model_name='boardexamattemptitem',
            constraint=models.UniqueConstraint(fields=('attempt', 'position'), name='unique_board_exam_item_position'),
        ),
        migrations.AddConstraint(
            model_name='boardexamattemptitem',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='unique_board_exam_item_question'),
        ),
    ]
