# Generated by Django 5.2.5 on 2026-09-25 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_question_lesson_source_review_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiknowledgeentry',
            name='lesson_rule',
            field=models.TextField(help_text='Short rule injected into future AI prompts (e.g. hyponatremia correction limits).'),
        ),
    ]
