# Generated by Django 5.2.5 on 2026-09-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_aiknowledgeentry_lesson_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lesson',
            name='interactive_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
