# Generated by Django 5.2.5 on 2026-09-30 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_lesson_media_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='confidence',
            field=models.CharField(choices=[('know', 'Know'), ('guessed', 'Guessed')], default='know', max_length=10),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='mode',
            field=models.CharField(choices=[('daily', 'Daily'), ('practice', 'Practice'), ('chapter', 'Chapter'), ('category', 'Category'), ('board_prep', 'Board Prep'), ('review', 'Review')], default='practice', max_length=20),
        ),
        migrations.CreateModel(
            name='BoardPrepSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('work_weekdays', models.JSONField(blank=True, default=list)),
                ('workday_question_target', models.PositiveIntegerField(default=25)),
                ('day_off_question_target', models.PositiveIntegerField(default=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board_prep_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Last48HourFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('formula', 'Formula'), ('biopsy', 'Biopsy'), ('toxicity', 'Drug toxicity'), ('electrolyte', 'Electrolyte algorithm'), ('dialysis', 'Dialysis number'), ('transplant', 'Transplant rejection'), ('pearl', 'Pearl'), ('miss', 'Repeated miss')], default='pearl', max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last48_facts', to='api.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last48_facts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
